WIP feat(intellij): add intellij refcard
ineat/refcards pull request #29
Opened 2020-02-05 17:06 UTC by cpoissonnier

2020-02-06 15:55 UTC, M3lkior commented
J'ajouterai aussi ce genre de contenu (en vrac) :
* Comment gerer plusieurs projets dans la meme fenêtre Idea (via project structure)
* Comment résoudre les problèmes d'annotation processing
* la commande `mvn idea:idea` dans un ecosysteme java  qui permet de remettre d'équerre la configuration maven d'un projet  
* peut etre un chapitre sur les runtimes configuration ? comment faire du remote debug, ajouter des variables d'environnement, etc

2020-02-07 09:59 UTC, mderelmfr commented
Pour ma part (et pour compléter la remarque de @M3lkior) j'aurai également ajouté :
- les conditions sur points d'arrêt
- la petite fenêtre "Evaluate expression", toujours bien pratique en debug

2020-02-07 10:00 UTC, mderacc commented
Pour ma part (et pour compléter la remarque de @M3lkior) j'aurai également ajouté :

- les conditions sur points d'arrêt
- la petite fenêtre "Evaluate expression", toujours bien pratique en debug

2020-02-13 12:39 UTC, lucas-dclrcq commented on intellij/FR.md
> +## Productivité
Je détaillerais beaucoup plus la partie postfix. Avec un ou plusieurs exemples custom pour montrer que c'est GÉNIAL.

2020-02-13 12:44 UTC, lucas-dclrcq commented on intellij/FR.md
> +Lorsque GIT nous fait défaut (parce qu'il n'est pas encore mis en place, ou qu'il s'agit de modifications ayant lieu entre deux commits), il est également possible d'utiliser un historique local.
J'ajouterais le chemin pour ouvrir l'outil. C'est peut être pas évident pour tout le monde que c'est dans le menu VCS.

2020-02-13 12:45 UTC, lucas-dclrcq commented on intellij/FR.md
> +De très bons outils existent déjà, mais IntelliJ permet également de faire ce type de comparaison avec le contenu du presse-papier, permettant ainsi de ne pas avoir à lancer une nouvelle application
Pareil j'ajouterais le chemin pour arriver à l"outil (Edit > Compare with clipboard)

2020-02-13 12:49 UTC, lucas-dclrcq commented on intellij/FR.md
> +Ils permettent de créer une nouvelle classe, niveau fichier JSON, XML, YAML, texte, ... directement dans l'IDE, mais sans être créé dans le dossier du projet courant.
Tu orientes l'interêt des scratch file sur la conf et le texte. Mais ça s'utilise vachement bien aussi pour tester un bout de code. Par exemple en java tu as accès à tout le classpath de ton projet, c'est vachement pratique pour tester un truc rapidement, faire un petit traitement ponctuel sur des données etc...

2020-02-13 12:51 UTC, lucas-dclrcq commented on intellij/FR.md
> +| Step over | `F8` | `F8` |
Je pense qu'il faut une partie entière sur le debugging, y'a beaucoup de fonctionnalités à détailler qui seraient intéressantes. (Typiquement toutes les facons de faire des breakpoint avancés, du type Exception BreakPoint)

2020-02-13 12:53 UTC, lucas-dclrcq commented on intellij/FR.md
> +## L'ours
L'ours ?

2020-09-23 14:18 UTC, cpoissonnier commented on intellij/FR.md
> +## Productivité
J'ai essayé d'ajouter un peu sur les postfix, mais je vois pas trop quoi rajouter :/

2020-09-23 14:19 UTC, cpoissonnier commented on intellij/FR.md
> +Lorsque GIT nous fait défaut (parce qu'il n'est pas encore mis en place, ou qu'il s'agit de modifications ayant lieu entre deux commits), il est également possible d'utiliser un historique local.
✅

2020-09-23 14:19 UTC, cpoissonnier commented on intellij/FR.md
> +De très bons outils existent déjà, mais IntelliJ permet également de faire ce type de comparaison avec le contenu du presse-papier, permettant ainsi de ne pas avoir à lancer une nouvelle application
✅

2020-09-23 14:19 UTC, cpoissonnier commented on intellij/FR.md
> +Ils permettent de créer une nouvelle classe, niveau fichier JSON, XML, YAML, texte, ... directement dans l'IDE, mais sans être créé dans le dossier du projet courant.
✅

2020-11-18 14:59 UTC, cpoissonnier commented on intellij/FR.md
> +| Step over | `F8` | `F8` |
✅

2020-11-18 16:14 UTC, cpoissonnier commented
Bon, vu que j'ai ENFIN du temps, j'ai pu prendre en compte la plupart des commentaires, mais pas tous.

Comme j'ai écrit dans l'intro : 
> L'objectif de ce document est de centraliser les fonctionnalités les plus utiles et apportant un gain significatif de productivité, sans être exhaustif, pour s'améliorer dans sa pratique quotidienne du développement.

Du coup j'ai pas pris en compte les remarques sur "comment résoudre les problèmes d'annnotation processing" et compagnie, vu que si on rencontre le souci, on a pas trop le choix et on corrige ça sur le moment. 

Bref, c'est pas un guide utilisateur, mais quelque chose qui permet de découvrir des fonctionnalités et raccourcis (le fait de rédiger tout ça m'a d'ailleurs permis de découvrir des trucs d'ailleurs 😄).

Je considère cette version comme étant release candidate ^^
J'attends vos relectures et votre validation !

2020-11-18 17:54 UTC, cpoissonnier commented
Penser à ajouter une taille max sur les images pour éviter les écarts entre les captures faites sur macOS et Windows

2020-12-04 16:09 UTC, M3lkior requested changes

2020-12-04 16:47 UTC, cpoissonnier commented on intellij/FR.md
> +L'objectif de ce document est de centraliser les fonctionnalités les plus utiles et apportant un gain significatif de productivité, sans être exhaustif, pour s'améliorer dans sa pratique quotidienne
C'était bien "et apportant", mais du coup, j'ai reformulé légèrement.

Dis moi si c'est mieux comme ça

2020-12-04 16:48 UTC, cpoissonnier commented on intellij/FR.md
> +## Transverse
Go pour général !

2020-12-04 16:50 UTC, cpoissonnier commented on intellij/FR.md
> +Aller plus loin
Ca n'est pas généralisé, j'ai supprimé cette ligne, un encart me semble suffire.

Dis-moi ce que t'en penses !

2020-12-04 16:50 UTC, cpoissonnier commented on intellij/FR.md
> +> S'il faut retenir un seul raccourci dans IntelliJ, il s'agit de celui de la recherche d'une action ("Find action") par son nom (Ctrl+Shift+A sur Windows/Linux et ⇧⌘A sur macOS).
Yep, c'est un oubli, bien vu 👍

2020-12-04 16:51 UTC, cpoissonnier commented on intellij/FR.md
> +> S'il faut retenir un seul raccourci dans IntelliJ, il s'agit de celui de la recherche d'une action ("Find action") par son nom (Ctrl+Shift+A sur Windows/Linux et ⇧⌘A sur macOS).
Ah, c'est un oubli qui avait été corrigé entre temps 😄

2020-12-04 17:01 UTC, cpoissonnier commented on intellij/FR.md
> +Bien que nous préconisions l'utilisation de Git à l'aide de lignes de commande, IntelliJ fournit des outils intéressants pour aider à la gestion du versioning avec une interface visuelle.
Vu que c'est dédié à du print, j'ai hésité, mais finalement j'ai pas mis de lien.

Si tu estimes que c'est mieux, dis le moi ! (j'ai pas suivi la manière dont vous aviez géré la transition md -> print, donc je me fais peut être du souci pour rien ^^)

2020-12-04 17:10 UTC, cpoissonnier commented on intellij/FR.md
> +Regénérer le sommaire (https://ecotrust-canada.github.io/markdown-toc/ ?)
Effectivement, difficile de suivre cette structure pour cette refcard qui est un peu hors cadre :/

Le fait de séparer les raccourcis des explications risque de rendre le tout moins lisible. Ton commentaire concernait une vieille version, tu penses toujours qu'il serait nécessaire de revoir la structure générale ?

2020-12-07 08:57 UTC, cpoissonnier commented on intellij/FR.md
> +
Bien vu, j'ai pas ajouté cette feature depuis un moment, du coup je l'avais oubliée.

Je l'ai ajoutée juste en dessous !

2020-12-11 08:54 UTC, cpoissonnier commented on intellij/FR.md
> +Il est plébiscité par la communauté des développeurs en raison de sa ergonomie, sa stabilité et des nombreuses fonctionnalités qu'il propose.
J'ai reformulé, dis, moi si c'est ok pour toi !

2020-12-11 10:33 UTC, M3lkior requested changes
une typo en plus de trouver

2020-12-11 10:33 UTC, M3lkior commented on intellij/FR.md
> +Grace à syntaxe proche des sélecteurs CSS, Emmet permet également d'écrire une structure de code très rapidement en HTML ou CSS.
```suggestion
Grace à une syntaxe proche des sélecteurs CSS, Emmet permet également d'écrire une structure de code très rapidement en HTML ou CSS.
```

2020-12-11 10:33 UTC, M3lkior commented on intellij/FR.md
> +Si vous n'êtes pas à l'aise avec l'utilisation de Git, nous vous recommandons vivement la lecture de notre Refcard sur le sujet !
```suggestion
Si vous n'êtes pas à l'aise avec l'utilisation de Git, nous vous recommandons vivement la lecture [de notre Refcard sur le sujet](https://github.com/ineat/refcards/blob/master/git/FR.md) ! 
```

2020-12-11 10:33 UTC, M3lkior commented on intellij/FR.md
> +Bien que nous préconisions l'utilisation de Git à l'aide de lignes de commande, IntelliJ fournit des outils intéressants pour aider à la gestion du versioning avec une interface visuelle.
lors de la mise en forme pour le print, tu pourras by-passer le lien

2020-12-11 10:33 UTC, M3lkior commented on intellij/FR.md
> +## L'ours
ca nous vienst de notre DA :)

2020-12-11 10:33 UTC, M3lkior commented on intellij/FR.md
> +Bien que nous préconisions l'utilisation de Git à l'aide de lignes de commande, IntelliJ fournit des outils intéressants pour aider à la gestion du versioning avec une interface visuelle.
mais a toi de voir

2020-12-11 10:44 UTC, cpoissonnier commented on intellij/FR.md
> +Grace à syntaxe proche des sélecteurs CSS, Emmet permet également d'écrire une structure de code très rapidement en HTML ou CSS.
Damn, faut vraiment que je dorme plus 😅

2020-12-11 10:58 UTC, germainlefebvre4 commented on intellij/FR.md
> +De très bons outils existent déjà, mais IntelliJ permet également de faire ce type de comparaison avec le contenu du presse-papier, permettant ainsi de ne pas avoir à lancer une nouvelle application
Quand tu as terminé la modification, tu peux ferme le commentaire avec le bouton "Resolve". Vous y gagnerez en visibilité

2020-12-11 11:02 UTC, cpoissonnier commented on intellij/FR.md
> +De très bons outils existent déjà, mais IntelliJ permet également de faire ce type de comparaison avec le contenu du presse-papier, permettant ainsi de ne pas avoir à lancer une nouvelle application
Merci pour la précision. Je l'avais pas fait pour Lucas, mais c'est fait maintenant !

2020-12-11 11:04 UTC, M3lkior commented on intellij/FR.md
> +Regénérer le sommaire (https://ecotrust-canada.github.io/markdown-toc/ ?)
ca ira pour cette refcard

2020-12-11 11:18 UTC, M3lkior commented on intellij/FR.md
> +De très bons outils existent déjà, mais IntelliJ permet également de faire ce type de comparaison avec le contenu du presse-papier, permettant ainsi de ne pas avoir à lancer une nouvelle application
Généralement c'est à la personne ayant ouvert la discussion de la résoudre après avoir validé les éléments avec le commiteur :) ca nous permet a nous, reviewer de voir toujours les discussions ouvertes pour les valider lors de la seconde passe

2020-12-11 11:23 UTC, cpoissonnier commented on intellij/FR.md
> +De très bons outils existent déjà, mais IntelliJ permet également de faire ce type de comparaison avec le contenu du presse-papier, permettant ainsi de ne pas avoir à lancer une nouvelle application
Je pense que c'est ce que le "moi du passé" a du se dire quand j'ai revu les commentaires de Lucas, effectivement ^^

2021-05-12 11:00 UTC, M3lkior approved these changes

2021-05-12 11:01 UTC, merged