Faithkovi patch
ineat/refcards pull request #63
Opened 2022-10-28 16:32 UTC by FaithKovi

Translate Vertx Refcard and add a link to README.md

2022-11-04 09:12 UTC, M3lkior commented
Hi @FaithKovi ; thanks for the PR and sorry for the reply delay (out of the Hacktoberfest period :/). Can you rebase your branch with the main ? i merged the git refcard since you start translating the vertx refcard

2022-11-15 10:04 UTC, FaithKovi commented
> Hi @FaithKovi ; thanks for the PR and sorry for the reply delay (out of the Hacktoberfest period :/). Can you rebase your branch with the main ? i merged the git refcard since you start translating the vertx refcard

I have rebased it. please review it so I can know if it was done correctly. This is my first time rebasing. @M3lkior

2022-11-17 10:01 UTC, M3lkior commented
hulm @FaithKovi  i think you miss your rebase because your PR already contains 3 commits (with 2 from master)
To correctly rebase your personal branch with the origin content, you need to
- invoke the `git pull ineat/master` cmd (if the ineat repository remote is named ineat) on your local master branch in order to update your master branch from the ineat repo master branch
- invoke the `git rebase master` on your patch-branch in order to synchronize your feature branch with the new modifications on master
- check now if your `FaithKovi:faithkovi-patch` branch have only 1 commits before master
- if yes, you can invoke `git push --force-with-lease` on your local `FaithKovi:faithkovi-patch` branch in order to update your remote version :)

2022-11-20 20:36 UTC, FaithKovi commented
@M3lkior I followed the steps you outlined above. Thank you. I have rebased the branch. Please review.

2022-12-23 09:19 UTC, M3lkior requested changes

2022-12-23 09:19 UTC, M3lkior commented on README.md
>  * [Git](git) | [FR](git/FR.md) | [EN](git/EN.md)
it seems that this file already have the conflicts markers ; can you fix this ?

2026-03-06 10:52 UTC, closed without merging